// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAxg8Z8th9P_GMNGinNtuGgOdo11SheFg',
    appId: '1:604899072081:web:0b1beac905fc96a04e8070',
    messagingSenderId: '604899072081',
    projectId: 'bookswap-3c7c5',
    authDomain: 'bookswap-3c7c5.firebaseapp.com',
    storageBucket: 'bookswap-3c7c5.firebasestorage.app',
    measurementId: 'G-ZL0SN9NYPY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyHnasr6aP6jPGGGF0y3S5gvDYeaUvUec',
    appId: '1:604899072081:android:b665b8d96e53143c4e8070',
    messagingSenderId: '604899072081',
    projectId: 'bookswap-3c7c5',
    storageBucket: 'bookswap-3c7c5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAQjVAM7KqemYtkZGwR4wTxWSDIgcZdzg',
    appId: '1:604899072081:ios:5fef1d50f060761a4e8070',
    messagingSenderId: '604899072081',
    projectId: 'bookswap-3c7c5',
    storageBucket: 'bookswap-3c7c5.firebasestorage.app',
    iosBundleId: 'com.example.bookswapApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAQjVAM7KqemYtkZGwR4wTxWSDIgcZdzg',
    appId: '1:604899072081:ios:5fef1d50f060761a4e8070',
    messagingSenderId: '604899072081',
    projectId: 'bookswap-3c7c5',
    storageBucket: 'bookswap-3c7c5.firebasestorage.app',
    iosBundleId: 'com.example.bookswapApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAxg8Z8th9P_GMNGinNtuGgOdo11SheFg',
    appId: '1:604899072081:web:b4e3ff9ab87c7baf4e8070',
    messagingSenderId: '604899072081',
    projectId: 'bookswap-3c7c5',
    authDomain: 'bookswap-3c7c5.firebaseapp.com',
    storageBucket: 'bookswap-3c7c5.firebasestorage.app',
    measurementId: 'G-CYDZXH0RJR',
  );

}